name: Claude Plan Review Response

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  call-review-workflow:
    uses: TomzxCode/llm-augmented-workflows/.github/workflows/claude-review.yml@main
    secrets: inherit
